### ISSUE TITLE
Melhorar arquivo copia_json.py

### ISSUE THREAD

**Issue by rafaelprr6** [LabTef-Ifes/espaco_inteligente_ifes#16]
O arquivo copia_json.py está copiando todas as configurações do 0.json para os demais arquivos. Observe que o packet_delay também é diferente para cada arquivo.

**Comment by braiansmarzaro** [comment]
O `copia_json.py` agora sobreescreve apenas os dados inputados pelo usuario, não mais copia todas as informações do 0.json
Pode conferir e fechar a issue
