### ISSUE TITLE
Atualizar Readme

### ISSUE THREAD

**Issue by rafaelprr6** [LabTef-Ifes/espaco_inteligente_ifes#5]
Testar o fps das câmeras do EI para atualizar as limitações das câmeras. **Feito**
Colocar a referência técnica dessas limitações. **Feito**
Verificar quais containeres permanecem ativos quando rodamos iniciar_principais_containeres.py. **Feito**
Adicionar tutorial para utilização das câmeras novas. **Feito**

**Comment by braiansmarzaro** [comment]
É necessário deixar claro também o modelo da câmera
Se possível, é importante também esclarecer outros parâmetros, como configurações da máquina e suporte da placa de rede, para reprodutibilidade no CREFES

**Comment by braiansmarzaro** [comment]
Falta a versão do python utilizada no projeto
É possível atualizar o python?
