### ISSUE TITLE
Falta arquivo "keymap.json"

### ISSUE THREAD

**Issue by braiansmarzaro** [LabTef-Ifes/espaco_inteligente_ifes#9]
Os arquivos "watch" fazem referencia a um "keymap.json" que não está no repositório

**Comment by rafaelprr6** [comment]
Alguns arquivos foram criados pelo Wyctor permaneceram localmente na máquina e não foram adicionados no GitHub. Adicionei o referido arquivo dentro da pasta 'dataset-creator'.
